name: FB to TG Autopost
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests facebook-page-scraper
          # Мы убрали попытку установки firefox-geckodriver через apt-get

      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # Добавляем параметр --headless в окружение, если скрипт его поддерживает
        run: python script.py

      - name: Save state
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add posted_ids.json
          git commit -m "Update posted IDs" || exit 0
          git push
